schema_version = "1.0.0"


id = "voxel_obj_blender_processor"
version = "1.1.0"
name = "Voxel Obj Processor"
tagline = "A tool designed to process .obj files exported from MagicaVoxel"
maintainer = "ccccco2@outlook.com"
type = "add-on"
blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-3.0-or-later",
]

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "/*.zip",
  ".DS_Store",
]